// Generated by jextract

package org.box3d;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef _Bool (b3CustomFilterFcn)(b3ShapeId, b3ShapeId, void *)
 * }
 */
public final class b3CustomFilterFcn {

    private b3CustomFilterFcn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        boolean apply(MemorySegment shapeIdA, MemorySegment shapeIdB, MemorySegment context);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Box3D.C_BOOL,
        b3ShapeId.layout(),
        b3ShapeId.layout(),
        Box3D.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Box3D.upcallHandle(Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static boolean invoke(MemorySegment funcPtr, MemorySegment shapeIdA, MemorySegment shapeIdB, MemorySegment context) {
        try {
            return (boolean) DOWN$MH.invokeExact(funcPtr, shapeIdA, shapeIdB, context);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

