// Generated by jextract

package org.box3d;

/**
 * {@snippet lang=c :
 * typedef b3Vec3 b3Pos
 * }
 */
public class b3Pos extends b3Vec3 {

    b3Pos() {
        // Should not be called directly
    }
}

