// Generated by jextract

package org.box3d;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

/**
 * {@snippet lang=c :
 * typedef float (b3TreeRayCastCallbackFcn)(const b3RayCastInput *, int, uint64_t, void *)
 * }
 */
public final class b3TreeRayCastCallbackFcn {

    private b3TreeRayCastCallbackFcn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        float apply(MemorySegment input, int proxyId, long userData, MemorySegment context);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Box3D.C_FLOAT,
        Box3D.C_POINTER,
        Box3D.C_INT,
        Box3D.C_LONG_LONG,
        Box3D.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Box3D.upcallHandle(Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static float invoke(MemorySegment funcPtr, MemorySegment input, int proxyId, long userData, MemorySegment context) {
        try {
            return (float) DOWN$MH.invokeExact(funcPtr, input, proxyId, userData, context);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

