// Generated by jextract

package org.box3d;

/**
 * {@snippet lang=c :
 * typedef b3Transform b3WorldTransform
 * }
 */
public class b3WorldTransform extends b3Transform {

    b3WorldTransform() {
        // Should not be called directly
    }
}

