// Generated by jextract

package org.box3d;

/**
 * {@snippet lang=c :
 * typedef b3CastOutput b3WorldCastOutput
 * }
 */
public class b3WorldCastOutput extends b3CastOutput {

    b3WorldCastOutput() {
        // Should not be called directly
    }
}

